version: 2

aliases:
  - &defaults
    working_directory: ~/melody
  - &node6_executor
    docker:
      - image: circleci/node:6
  - &node8_executor
    docker:
      - image: circleci/node:8
  - &node10_executor
    docker:
      - image: circleci/node:10
  - &default_executor
    <<: *node10_executor
  - &repo_key
    repo-{{ .Branch }}-{{ .Revision }}
  - &coverage_key
    coverage-{{ .Branch }}-{{ .Revision }}
  - &base_config_key
    base-config-{{ .Branch }}-{{ .Revision }}
  - &yarn_cache_key
    yarn-sha-{{ checksum "yarn.lock" }}
  - &restore_repo
    restore_cache:
      keys:
        - *repo_key
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /release\/.*/
  - &execute_on_release
    filters:
      tags:
        only: /(v)?[0-9]+(\.[0-9]+)*/
      branches:
        ignore:
          - /.*/

jobs:
  prepare:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - checkout
      - restore_cache:
          key: *base_config_key
      - run:
          name: 'Base environment setup'
          command: echo "//registry.verdaccio.org/:_authToken=${REGISTRY_TOKEN}" > ~/.npmrc
      - save_cache:
          key: *base_config_key
          paths:
            - ~/.npmrc
            - ~/.gitconfig
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install Js dependencies and Build
          command: yarn install --no-progress --no-lockfile
      - save_cache:
          key: *yarn_cache_key
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
      - save_cache:
          key: *repo_key
          paths:
            - ~/melody
  lint:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - run:
          name: lint
          command: yarn lint

  test_bundlesize:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - run:
          name: Test BundleSize
          command: yarn bundlesize

  test_node6:
    <<: *defaults
    <<: *node6_executor
    steps:
      - *restore_repo
      - run:
          name: Test with Node 6
          command: yarn test

  test_node8:
    <<: *defaults
    <<: *node8_executor
    steps:
      - *restore_repo
      - run:
          name: Test with Node 8
          command: yarn test

  test_node10:
    <<: *defaults
    <<: *node10_executor
    steps:
      - *restore_repo
      - run:
          name: Test with Node 10
          command: yarn run test
      - save_cache:
          key: *coverage_key
          paths:
          - coverage
  
  canary_release:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - run:
          name: canary
          command: yarn lerna publish --no-git-tag-version --no-push --no-git-reset --exact --force-publish=* --canary --yes --dist-tag ${CIRCLE_BRANCH} --preid ${CIRCLE_SHA1} --registry https://registry.verdaccio.org


  # coverage:
  #   <<: *defaults
  #   <<: *default_executor
  #   steps:
  #     - *restore_repo
  #     - restore_cache:
  #         key: *coverage_key
  #     - run:
  #         name: Publish coverage
  #         command: yarn run coverage:publish
  #     - store_artifacts:
  #         path: coverage/clover.xml
  #         prefix: tests
  #     - store_artifacts:
  #         path: coverage
  #         prefix: coverage
  #     - store_test_results:
  #         path: coverage/clover.xml

  # publish_package:
  #   <<: *defaults
  #   <<: *default_executor
  #   steps:
  #     - *restore_repo
  #     - restore_cache:
  #         key: *base_config_key
  #     - run:
  #         name: Publish
  #         command: yarn publish

workflows:
  version: 2
  workflow:
    jobs:
      - prepare:
          <<: *ignore_non_dev_branches
      - lint:
          requires:
            - prepare
      - test_node6:
          requires:
            - prepare
      - test_node8:
          requires:
            - prepare
      - test_node10:
          requires:
            - prepare
      - test_bundlesize:
          requires:
            - test_node6
            - test_node8
            - test_node10
      - canary_release:
          requires:
            - test_node6
            - test_node8
            - test_node10
          filters:
            branches:
              only:
                - /^(?!.*?master).*/
      # - coverage:
      #     requires:  
      #       - test_bundlesize
      # - publish_package:
      #     requires:
      #       - coverage
      #     <<: *execute_on_release
